# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20171008_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literature',
            name='lit_genre',
        ),
    ]
