# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-08 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20171009_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='literature',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
